### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by Spawn944** [woctezuma/steampy-buy-orders#3]
I don't see the set_buy_orders.py file. Where is it? I can only see the license and readme files.

**Comment by woctezuma** [comment]
I have not yet committed any Python file, because the code is messy. Plus, the script automatically sets buy orders for some items which I monitor for profit, but I have paused doing so as the price of sacks of gems has crashed anyway since the Winter Sale 2022.

Meanwhile, you can refer to examples of usage for `create_buy_order()` and `cancel_buy_order()` in the README of [`steampy`][steampy]:

```python
steam_client = SteamClient(self.credentials.api_key)
steam_client.login('MY_USERNAME', 'MY_PASSWORD', 'PATH_TO_STEAMGUARD_FILE')
response = steam_client.market.create_buy_order("AK-47 | Redline (Field-Tested)", "1034", 2, GameOptions.CS, Currency.EURO)
buy_order_id = response["buy_orderid"]
```

```python
steam_client = SteamClient(self.credentials.api_key)
steam_client.login('MY_USERNAME', 'MY_PASSWORD', 'PATH_TO_STEAMGUARD_FILE')
buy_order_id = "some_buy_order_id"
response = steam_client.market.cancel_buy_order(buy_order_id)
```

[steampy]: <https://github.com/bukson/steampy>

**Comment by yesworId** [comment]
@Spawn944 You can find bot, which creates buy orders on my repositories. https://github.com/yesworId/BuyOrderBot/tree/master

Feel free to give your suggestions.

Also woctezuma, if we could work together in any chance. We could systemize this mess together. DM me in discord, if you are interested. Merci beaucoup!

**Comment by woctezuma** [comment]
Thank you for the offer, but I don't have the time for working on this for now!

I will look into your repository. Here is the link for other people who could be interested in this project:
- https://github.com/YESW0RLD/BuyOrderBot

**Comment by yesworId** [comment]
Merci, Je te comprends.

**Comment by woctezuma** [comment]
For info, I have found this script which may be the messy script which I mentioned:
- https://github.com/woctezuma/steampy/blob/buy-orders/secrets_main.py

I don't think it would be of much use in this state, plus it is not doing anything fancy, but I may as well post it in this issue. 😛 

**Edit:** I have moved the script to this repository and deleted the branch from the fork linked above.
